# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wrap_version <- function() {
    .Call('xpdf_wrap_version', PACKAGE = 'xpdf')
}

wrap_pdftotext <- function(R_input, R_output, firstPage, lastPage, physLayout, tableLayout, linePrinter, rawOrder, fixedPitch, fixedLineSpacing, clipText, R_enc, R_eol, noPageBreaks, R_opw, R_upw, quiet, R_config) {
    .Call('xpdf_wrap_pdftotext', PACKAGE = 'xpdf', R_input, R_output, firstPage, lastPage, physLayout, tableLayout, linePrinter, rawOrder, fixedPitch, fixedLineSpacing, clipText, R_enc, R_eol, noPageBreaks, R_opw, R_upw, quiet, R_config)
}

